### ISSUE TITLE
帖子内留言框 头像 undefined 

### ISSUE THREAD

**Issue by RikkaBlue** [7nights/get-v2ex#2]
![image](https://user-images.githubusercontent.com/46104879/67140405-b0f99280-f28c-11e9-9a1b-dfc770853e3d.png)

```html
<img class="avatar" src="undefined">
```
通知历史正常，回复正常，但是用户似乎没有定义。
![image](https://user-images.githubusercontent.com/46104879/67140435-e4d4b800-f28c-11e9-935a-0847b2904554.png)

**Comment by 7nights** [comment]
之前匹配用户信息的正则没考虑到没有设置用户签名的状态，已经修复，感谢反馈。

https://github.com/7nights/get-v2ex/commit/358bf0087194403562063dc5cc0b46725175aecd
