### ISSUE TITLE
创建主题失败 `once: 'undefined'

### ISSUE THREAD

**Issue by RikkaBlue** [7nights/get-v2ex#8]
![image](https://user-images.githubusercontent.com/46104879/68099303-b564b300-fefc-11e9-9732-185530259fb6.png)

```
1|v2ex     | current latest version is: 1.1.3
1|v2ex     | No updates found.

```

**Comment by 7nights** [comment]
是从节点页面点击创建主题进入的吗？有没有在创建主题页面上刷新过？

**Comment by RikkaBlue** [comment]
> 是从节点页面点击创建主题进入的吗？有没有在创建主题页面上刷新过？

是的;没有过

**Comment by 7nights** [comment]
访问一下 `/api/recent` 看看 `userInfo` 对象里是否存在 `csrf` 属性，正常情况下应该有 `username`, `avatar` 和 `csrf`.

**Comment by RikkaBlue** [comment]
没有 `csrf` 属性，只有 `username` 和 `avatar`

**Comment by 7nights** [comment]
`csrf` 是从 https://github.com/7nights/get-v2ex/blob/master/configs/regs.js#L5 这个正则匹配出来的，我试了不同账号，目前没有发现匹配不到的情况……你用自己的账号访问 www.v2ex.com 查看源码能看到能命中这段正则的内容吗？直接搜 `signout` 应该就能搜到。
